name: sync-action
description: Github Action to sync with Bitbucket repository.
inputs:
  DST_USER:
    description: Bitbucket username of the destination repository.
    required: true
  DST_PASS:
    description: Bitbucket app password of the destination repository.
    required: true
  DST_SSH:
    description: Bitbucket SSH key to use for the sync.
    required: true
  BITBUCKET_WORKSPACE:
    description: Bitbucket Workspace.
    required: true
  BITBUCKET_PROJECT:
    description: Bitbucket Project Key.
    required: true
  KNOWN_HOSTS:
    description: The contents of a SSH known_hosts file for host key verification. (If not provided, the host key will not be verified.)
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
